#!/bin/bash
# This file is a part of quicksave project.
# Copyright 2017 Aleksander Gajewski <adiog@quicksave.io>.

cd $(dirname $0)

INPUT=$1
OUTPUT=$2
shift 2
SPECIFIC_BEANS_ONLY=$*

OUTPUT_DIR=$OUTPUT/generated/databaseBean
mkdir -p $OUTPUT_DIR

if [[ -z "$SPECIFIC_BEANS_ONLY" ]];
then
    BEANS=$(ls -1 $INPUT/*.json)
else
    for BEAN in $SPECIFIC_BEANS_ONLY;
    do
        BEANS="$BEANS $BEAN.json"
    done
fi

(
echo "// This file is an AUTOGENERATED part of beans project."
echo "// Copyright (c) 2017 Aleksander Gajewski <adiog@quicksave.io>."
echo ""
echo "#pragma once"
echo ""
) > $OUTPUT_DIR/DatabaseBeans.h

for bean_file in $BEANS;
do
    BEAN=$(basename $bean_file);
    echo "Genarating database $BEAN ..."
    python3 generate_postgres.py $INPUT $BEAN | clang-format > $OUTPUT_DIR/DatabaseBean${BEAN/.json/.h}
    echo "#include <databaseBean/DatabaseBean${BEAN/.json/.h}>" >> $OUTPUT_DIR/DatabaseBeans.h
    echo "... genarating database $BEAN [DONE]"
done
