#!/bin/bash
# This file is a part of quicksave project.
# Copyright 2017 Aleksander Gajewski <adiog@quicksave.io>.

cd $(dirname $0)

INPUT=${1:-../../beans}
OUTPUT=${2:-../../..}

(
echo "// This file is an AUTOGENERATED part of beans project."
echo "// Copyright (c) 2017 Aleksander Gajewski <adiog@quicksave.io>."
echo ""
echo "#pragma once"
echo ""
) > $OUTPUT/generated/qsgen/databaseBean/DatabaseBeans.h
