#!/bin/bash
# This file is a part of quicksave project.
# Copyright 2017 Aleksander Gajewski <adiog@quicksave.io>.

cd $(dirname $0)

INPUT=$1
OUTPUT=$2

mkdir -p $OUTPUT/js/generated
QSBEANS_JS=$OUTPUT/js/generated/jsbeans.min.js

(
echo ''
echo '// This file is an AUTOGENERATED part of quicksave project.'
echo '// Copyright (c) 2017 Aleksander Gajewski <adiog@quicksave.io>.'
) > $QSBEANS_JS

for bean in Tag Item RichItem;
do
    python3 generate.py $INPUT ${bean}.json >> $QSBEANS_JS
done
