import json
import sys
import re

BODY="""// This file is an AUTOGENERATED part of beans project.
// Copyright (c) 2017 Aleksander Gajewski <adiog@quicksave.io>.

class ___BEAN___Bean extends Bean
{
}
register_bean_spec("___BEAN___Bean", ___BEAN___Bean, '___SPEC___');
"""


def make_bean(bean_path, bean_filename):
    with open(bean_path + '/' + bean_filename, 'r') as bean_file:
        bean_spec = re.sub(r'\n', '', bean_file.read())
    print(
        re.sub('___BEAN___', bean_filename[:-5],
        re.sub('___SPEC___', bean_spec,
                 BODY)))

if __name__ == '__main__':
    make_bean(sys.argv[1], sys.argv[2])
