#!/bin/bash
# This file is a part of quicksave project.
# Copyright 2017 Aleksander Gajewski <adiog@quicksave.io>.

cd $(dirname $0)

GENERATOR=generate_supersonic_memory.py
IO_QUICKSAVE_BEANS_DIR=../../beans

OUTPUT_DIR=../../../supersonic_quicksave_generated/qsgen/supersonicBean
mkdir -p ${OUTPUT_DIR}

(
echo "// This file is an AUTOGENERATED part of beans project."
echo "// Copyright (c) 2017 Aleksander Gajewski <adiog@quicksave.io>."
echo ""
echo "#pragma once"
echo ""
) > ${OUTPUT_DIR}/SupersonicBeans.h

for bean in Meta File Action Tag Key Perspective;
do
  output=SupersonicBean${bean}.h
  python3 ${GENERATOR} ${IO_QUICKSAVE_BEANS_DIR} ${bean}.json | clang-format > ${OUTPUT_DIR}/${output}
  echo "#include <qsgen/supersonicBean/${output}>" >> ${OUTPUT_DIR}/SupersonicBeans.h
done
