// This file is an AUTOGENERATED part of beans project.
// Copyright (c) 2017 Aleksander Gajewski <adiog@quicksave.io>.

#pragma once

#include <iostream>
#include <string>

#include <folly/Format.h>

#include <sqlpp11/alias_provider.h>
#include <sqlpp11/char_sequence.h>
#include <sqlpp11/column_types.h>
#include <sqlpp11/custom_query.h>
#include <sqlpp11/functions.h>
#include <sqlpp11/insert.h>
#include <sqlpp11/multi_column.h>
#include <sqlpp11/remove.h>
#include <sqlpp11/select.h>
#include <sqlpp11/table.h>
#include <sqlpp11/transaction.h>
#include <sqlpp11/update.h>

#include <sqlpp11/sqlite3/connection.h>
#include <sqlpp11/postgresql/connection.h>

#include <CppBeans.h>

#include <qsgen/ABI.h>
#include <qsgen/orm/sqlppTables.h>

#include <qs/util/hash.h>


namespace qs {

template <typename T>
class ORM;
}
