#!/bin/bash
# Copyright 2017 Aleksander Gajewski <adiog@brainfuck.pl>
#   created:  sob, 18 lut 2017, 13:53:28
#   modified: sob, 18 lut 2017, 13:53:36

cd $(dirname $0)

INPUT=$1
OUTPUT=$2
shift 2
SPECIFIC_BEANS_ONLY=$*

echo INPUT=$INPUT
echo OUTPUT=$OUTPUT
echo SPECIFIC_BEANS_ONLY=$SPECIFIC_BEANS_ONLY

read
OUTPUT_DIR=$OUTPUT/generated/
mkdir -p $OUTPUT_DIR
read
if [[ -z "$SPECIFIC_BEANS_ONLY" ]];
then
    BEANS=$(ls -1 $INPUT/*.json)
else
    for BEAN in $SPECIFIC_BEANS_ONLY;
    do
        BEANS="$BEANS $BEAN.json"
    done
fi
echo $BEANS
read
(
echo '# This file is an AUTOGENERATED part of beans project.'
echo '# Copyright (c) 2017 Aleksander Gajewski <adiog@quicksave.io>.'
echo ''
echo 'import pybeans'
echo ''
) > ${OUTPUT_DIR}/QsBeans.py

for bean_file in $BEANS;
do
    BEAN=$(basename $bean_file);
    echo "Genarating $BEAN ..."
    python3 generate.py $INPUT ${BEAN} >> $OUTPUT_DIR/QsBeans.py
    echo "... genarating $BEAN [DONE]"
done

touch $OUTPUT_DIR/__init__.py

